## Download the dataset

In [ ]:
#Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
# Path to the dataset
real_estate_file_path = '/content/drive/MyDrive/ds/hw/Realestate.csv'

# Create an object that will contain our dataset
real_estate_data = pd.read_csv(real_estate_file_path)
real_estate_data.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

## Describe the dataset
A dataset that contains the transaction date, the house age, the distance to the nearest MRT, the number of convenience stores, latitude, longitude. The price of unit area.

Print the statistical description of the first 100 records of the dataset

In [ ]:
Select100 = real_estate_data.head(100)
Select100.describe()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
count,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,2013.16170,18.472000,1133.658832,4.170000,24.969346,121.533141,38.440000
std,29.011492,0.29955,11.516489,1308.867454,2.867635,0.012994,0.015743,13.481255
min,1.000000,2012.66700,0.000000,23.382840,0.000000,24.941550,121.484580,13.200000
25%,25.750000,2012.91700,9.850000,319.389925,1.000000,24.963045,121.529468,26.875000
50%,50.500000,2013.08300,16.450000,533.476200,4.000000,24.973490,121.539130,39.800000
75%,75.250000,2013.41700,29.775000,1420.772500,6.000000,24.977283,121.543910,48.025000
max,100.000000,2013.58300,40.900000,5512.038000,10.000000,25.014590,121.552820,70.100000

## Use all available parameters for forecasting

In [ ]:
real_estate_data.columns
x_names =['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']
X = real_estate_data[x_names]
X.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2012.917,19.5,306.59470,9,24.98034,121.53951
2,2013.583,13.3,561.98450,5,24.98746,121.54391
3,2013.500,13.3,561.98450,5,24.98746,121.54391
4,2012.833,5.0,390.56840,5,24.97937,121.54245

## Define the forecasting objective (price)

In [ ]:
y = real_estate_data['Y house price of unit area']
y.head()

0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: Y house price of unit area, dtype: float64

## Write a model on the DecisionTreeRegressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# Define the module. Specify the number for random_state to guarantee the same results every time you run the code
real_estate_model = DecisionTreeRegressor(random_state=1)

# Fit the model!
real_estate_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

## Make a price forecast for the first 5 rows

In [ ]:
print("We make a forecast for the first 5 houses:")
# print(X.head())
print("The following are the prices that we can forecast:")
print(real_estate_model.predict(X.head()))
print(y.head())

We make a forecast for the first 5 houses:
The following are the prices that we can forecast:

NameError: name 'real_estate_model' is not defined

## Create a new model and forecast the price of a house using only the coordinates of the house

In [ ]:
coordinates =  ['X5 latitude','X6 longitude']
X1 = real_estate_data[coordinates]
real_estate_model1 = DecisionTreeRegressor(random_state=1)

# Fit the modetl!
real_estate_model1.fit(X1, y)

print(real_estate_model1.predict(X1.head()))
print(y.head())

[37.9        42.2        47.5        47.5        45.18333333]
0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: Y house price of unit area, dtype: float64

## Indicators of the price of which houses are not accurately forecasted
Indicators of 3,4,5 houses were forecasted inaccurately